spring:
  application:
    name : libraryapi
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: user-name
    password: strong-password
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: update #data definition language
      ddl-auto: none #data definition language
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 31394710678-kbg6jtnv7j3nj27v87np0ekpo2fks9em.apps.googleusercontent.com
            client-secret: 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
